In [1]:
import numpy as np
import torch
from torchegranate.distributions import Categorical
from torchegranate.distributions import ConditionalCategorical
from torchegranate.bayesian_network import BayesianNetwork

line = Categorical([[0.5, 0.3, 0.2]]) #Line 22, 24, 6
time_of_day = Categorical([[0.5, 0.5]]) # Day or Night (50% chance)
wagons = ConditionalCategorical(np.array([[
    #Line 22
    [[0.3, 0.7], [0.1, 0.9]], #Day/Night
    #Line 24
    [[0.2, 0.8], [0.2, 0.8]],
    #Line 6
    [[0.9, 0.1], [1.0, 0.0]]
]]))
destination = ConditionalCategorical(np.array([
    #Line 22
    [[0.1, 0.9],
    #Line 24
     [0.9, 0.1],
    #Line 6
     [0.1, 0.9]]
]))

model = BayesianNetwork([line, time_of_day, wagons, destination], [(line, wagons), (time_of_day, wagons), (line, destination)])

In [2]:
#Night scenario with a single wagon
X = torch.masked.masked_tensor(torch.tensor([[-1, 1, 0, -1]]),
                               mask=torch.tensor([[False, True, True, False]]))
model.predict_proba(X)

c:\Users\Ismael\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\masked\maskedtensor\core.py:156: UserWarning: The PyTorch API of MaskedTensors is in prototype stage and will change in the near future. Please open a Github issue for features requests and see our documentation on the torch.masked module for further information about the project.
  warnings.warn(("The PyTorch API of MaskedTensors is in prototype stage "


[tensor([[0.1613, 0.1935, 0.6452]]),
 tensor([[0., 1.]]),
 tensor([[1., 0.]]),
 tensor([[0.2548, 0.7452]])]

In [3]:
#Number of wagons on Line 22 on destination
X = torch.masked.masked_tensor(torch.tensor([[0, -1, -1, 1]]),
                               mask=torch.tensor([[True, False, False, True]]))
model.predict_proba(X)

[tensor([[1., 0., 0.]]),
 tensor([[0.5000, 0.5000]]),
 tensor([[0.2000, 0.8000]]),
 tensor([[0., 1.]])]