## Monty Hall Problem

#### The game involves three doors, given that behind one of these doors is a car and the remaining two have goats behind them. So you start by picking a random door, say #2. On the other hand, the host knows where the car is hidden and he opens another door, say #1 (behind which there is a goat). Here's the catch, you're now given a choice, the host will ask you if you want to pick door #3 instead of your first choice, i.e. #2. Is it better if you switch your choice or should you stick to your first choice?

In [1]:
import numpy as np
import torch
from torchegranate.distributions import Categorical
from torchegranate.distributions import ConditionalCategorical
from torchegranate.bayesian_network import BayesianNetwork

guest = Categorical([[1./3, 1./3, 1./3]])  # The door selected by the guest is completely random
prize = Categorical([[1./3, 1./3, 1./3]])  # The door containing the prize is also a random process
monty = ConditionalCategorical(np.array([[ # The door selected by Monty depends on guest and prize
     [[0.0, 0.5, 0.5], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0]], # 00, 01, 02
     [[0.0, 0.0, 1.0], [0.5, 0.0, 0.5], [1.0, 0.0, 0.0]], # 10, 11, 12
     [[0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.5, 0.5, 0.0]]  # 20, 21, 22
]]))

model = BayesianNetwork([guest, prize, monty], [(guest, monty), (prize, monty)])

In [15]:
X = torch.masked.masked_tensor(torch.tensor([[2, 0, 1]]), mask=torch.tensor([[True, False, True]]));
model.predict(X)

tensor([[2, 0, 1]])

In [16]:
model.predict_proba(X)

[tensor([[0., 0., 1.]]),
 tensor([[0.6667, 0.0000, 0.3333]]),
 tensor([[0., 1., 0.]])]